# Generated by Django 3.1.14 on 2023-08-16 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
                ('publish', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
